# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: valkerie CI

on:
  push:
    branches: [ "main","dev","gh-pages" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
  
        - name: Deploy to Production
          if: github.event_name == 'push' && github.ref == 'refs/heads/main'
          run: npm run deploy:release
  
        - name: Deploy to Develop
          if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
          run: npm run deploy:development
  
        - name: Deploy to gh-pages
          if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/gh-pages')
          run: npm run deploy:github-pages
